# Generated by Django 4.0 on 2021-12-28 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 16, 3, 56, 678643)),
        ),
    ]
