# Generated by Django 4.0 on 2021-12-28 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_alter_comentario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 16, 14, 2, 787818)),
        ),
    ]